### ISSUE TITLE
I don't understand how this works

### ISSUE THREAD

**Issue by ghost** [neykov/syno-magnet#1]
How does this work? I installed it but can't figure out how it does anything

**Comment by bxlouis** [comment]
Does not work for me either with my DS918+. Tried with Safari and Chrome and I don't understand how to make this work.

**Comment by Minorli** [comment]
How to disable this feature ？ its a so boring feature.

**Comment by neykov** [comment]
Try it on Chrome or Firefox (does not work on Safari):
  * Make sure you have "Download Station" installed
  * Install the magnet app.
  * Open it from the apps list. You should see a "register" button there. Clicking it will register the app to open magnet links for torrents.
  * Now go and click on a torrent magnet link (links starting with `magnet:`). This will add the torrent to the "Download Station" app.
  * Open "Download Station" - you should see the torrent there.

**Comment by neykov** [comment]
Here's how it looks like when it's all set up:
---
![magnet](https://user-images.githubusercontent.com/3612111/64451137-403b5400-d0ec-11e9-8558-179909e9fbef.gif)

**Comment by kydxone** [comment]
How to disable this feature ？ its a so boring feature.

**Comment by neykov** [comment]
Disabling has been tackled in https://github.com/neykov/syno-magnet/issues/2.
