### ISSUE TITLE
root issue with new DSM 7

### ISSUE THREAD

**Issue by alandproject** [neykov/syno-magnet#3]
<img width="1226" alt="Screenshot 2020-12-09 at 7 14 03 PM" src="https://user-images.githubusercontent.com/47828572/101662921-beef1180-3a52-11eb-9909-4e0f4bc17cec.png">
Need an update :)

**Comment by neykov** [comment]
Let me investigate.

**Comment by neykov** [comment]
SynoCommunity is in the process of implementing DSM 7 support. For details see:
* https://github.com/SynoCommunity/spksrc/issues/4170
* https://github.com/SynoCommunity/spksrc/issues/4215

I will release a new package as soon as there's support for DSM 7.

**Comment by neykov** [comment]
Here's a re-packaged release of syno-magnet which can be installed manually.

[syno-magnet_noarch-all_1.0-3.spk.zip](https://github.com/neykov/syno-magnet/files/5761731/syno-magnet_noarch-all_1.0-3.spk.zip)

Unzip and then upload the spk in Package Center.

The configuration to open Download Station directly has changed in DSM7. Here's a screenshot of the location for setting an alias:
<img width="1157" alt="Screenshot 2021-01-03 at 16 23 49" src="https://user-images.githubusercontent.com/3612111/103481031-d23a9600-4de0-11eb-8def-08a947eda088.png">

**Comment by alandproject** [comment]
Perfect! it works 👍 
thank you.
