### ISSUE TITLE
No task created after open magnet link

### ISSUE THREAD

**Issue by tuyennn** [neykov/syno-magnet#8]
- Download Station 3.9.3-4609
- DMS 7.0

I'm able to register magnet link with Download station and open download station, but doesn't seem any task created after Download Station opens.

**Comment by neykov** [comment]
Can you open the Networking tab of Developer tools and capture the communication. If there's any error in the process can you share the details.

**Comment by tuyennn** [comment]
@neykov thanks for the feedback, It came out my Nas network problem rather the module bug
