### ISSUE TITLE
Download not added

### ISSUE THREAD

**Issue by FezVrasta** [neykov/syno-magnet#9]
After I click on a Magnet I'm brought to my NAS interface but nothing happens after that.

The URL looks like:

https://abcdef.direct.quickconnect.to:5001/webman/3rdparty/syno-magnet/index.html#download=magnet%3A%3Fxt%3Du[redacted]

I'm on DSM 7.1-42661

**Comment by neykov** [comment]
@FezVrasta can you record a gif of this happening along with the Network tab in Developers open and visible. Then attach to this ticket.

**Comment by FezVrasta** [comment]
My NAS is being serviced, as soon I receive it back I'll test it again, thanks!

**Comment by FezVrasta** [comment]
After I received the NAS back and reinstalled everything it started working, thanks anyways!
